### ISSUE TITLE
Add listener event on Window doesn't works

### ISSUE THREAD

**Issue by katan** [GaurangTandon/checkEventAdded#1]
Hi Gaurang,
First at all, thanks for sharing this script. I found a issue when try to add a listener on a Window Object, the problem is dataset variable isn't defined.
I fixed it adding this line: "if (!this.dataset) this.dataset = {};"  on the return function of makeListener.

Best regards.

**Comment by GaurangTandon** [comment]
Hi, yes, I checked it out. You're right. I didn't ever need to attach listeners to `Window` but one might need to so yeah it's needed. Thanks for checking this out! :)

**Comment by GaurangTandon** [comment]
Please verify that the new files work for you.
